export type Job = {
  id: string;
  name: string;
  category: string;
  summary: string;
  keywords: string[];
  skills: string[];
  bullets: { label: string; example: string }[];
  coverTip: string;
};

export const JOB_CATEGORIES: { id: string; label: string }[] = [
  { id: "tech", label: "Technology & IT" },
  { id: "healthcare", label: "Healthcare" },
  { id: "trades", label: "Trades & Construction" },
  { id: "business", label: "Business & Finance" },
  { id: "education", label: "Education" },
  { id: "creative", label: "Creative & Media" },
  { id: "hospitality", label: "Hospitality & Retail" },
  { id: "other", label: "Logistics, Legal & Service" },
];

export const JOBS: Job[] = [
  // ── Technology & IT (12) ─────────────────────────────────────────
  {
    id: "software-engineer",
    name: "Software Engineer",
    category: "tech",
    summary: "Software engineers design, build, and maintain applications — from web platforms to backend systems. Recruiters scan for clean code, strong problem-solving, and shipped projects.",
    keywords: ["JavaScript", "TypeScript", "React", "Node.js", "API development", "CI/CD", "Git", "Agile", "Unit testing", "Cloud (AWS/Azure/GCP)"],
    skills: ["System design", "Code reviews", "Performance optimization", "Version control", "Documentation", "Pair programming"],
    bullets: [
      { label: "Impact", example: "Built and shipped a customer-facing web platform used by 10,000+ monthly users, cutting load times by 40%." },
      { label: "Ownership", example: "Owned feature delivery end-to-end — design, implementation, tests, and deployment — across 6 major releases." },
      { label: "Collaboration", example: "Collaborated with product and design teams in Agile sprints, shipping 20+ features with a 98% on-time rate." },
    ],
    coverTip: "Open with the problem you solved, not your title — employers in this market skim the first paragraph and decide in seconds.",
  },
  {
    id: "frontend-developer",
    name: "Frontend Developer",
    category: "tech",
    summary: "Frontend developers turn designs into fast, accessible interfaces. A strong resume shows real projects, modern frameworks, and attention to performance and UX detail.",
    keywords: ["HTML5", "CSS3", "JavaScript", "TypeScript", "React", "Next.js", "Tailwind CSS", "Accessibility (a11y)", "Responsive design", "Performance"],
    skills: ["Component libraries", "State management", "Web accessibility", "Cross-browser testing", "UI animation", "Design systems"],
    bullets: [
      { label: "Build", example: "Rebuilt the marketing site with Next.js, improving Lighthouse performance scores from 62 to 96." },
      { label: "Accessibility", example: "Led an accessibility pass across 30+ pages, bringing the product to WCAG 2.1 AA compliance." },
      { label: "Velocity", example: "Introduced reusable component patterns that reduced feature build time by 30%." },
    ],
    coverTip: "Link your portfolio or live projects — recruiters click it before they read a single bullet point.",
  },
  {
    id: "backend-developer",
    name: "Backend Developer",
    category: "tech",
    summary: "Backend developers build the APIs, databases, and services that power products. Resumes that show scale, reliability, and clean architecture stand out.",
    keywords: ["Node.js", "Python", "Java", "SQL", "PostgreSQL", "REST APIs", "GraphQL", "Docker", "Microservices", "Caching"],
    skills: ["Database design", "API security", "Load testing", "Message queues", "Monitoring & logging", "System architecture"],
    bullets: [
      { label: "Scale", example: "Designed and scaled a REST API serving 2M+ requests per day with 99.9% uptime." },
      { label: "Reliability", example: "Reduced error rates from 1.2% to 0.1% by introducing structured logging and alerting." },
      { label: "Speed", example: "Cut API response times by 60% with caching and query optimization." },
    ],
    coverTip: "Quantify anything you can — uptime, requests per second, or latency wins prove your engineering impact.",
  },
  {
    id: "full-stack-developer",
    name: "Full-Stack Developer",
    category: "tech",
    summary: "Full-stack developers own the whole product — frontend, backend, and deployment. Resumes should show breadth of shipped projects and end-to-end ownership.",
    keywords: ["JavaScript", "TypeScript", "React", "Node.js", "SQL", "REST APIs", "Git", "CI/CD", "Cloud", "Agile"],
    skills: ["Full product ownership", "API design", "Database modeling", "Deployment automation", "Testing", "Performance"],
    bullets: [
      { label: "End-to-end", example: "Built a full-stack SaaS from architecture to launch — React frontend, Node API, and PostgreSQL database." },
      { label: "Shipping", example: "Shipped 15+ features in one year across frontend, backend, and infrastructure." },
      { label: "Automation", example: "Set up CI/CD pipelines that cut deployment time from hours to minutes." },
    ],
    coverTip: "Show at least one complete product — employers hire full-stack developers for ownership, not just skills.",
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    category: "tech",
    summary: "Data scientists turn raw data into insight and prediction. Strong resumes pair statistical rigor with business outcomes and clean storytelling.",
    keywords: ["Python", "SQL", "Machine Learning", "Pandas", "NumPy", "Scikit-learn", "TensorFlow", "Statistics", "Data visualization", "A/B testing"],
    skills: ["Model building", "Feature engineering", "Statistical analysis", "Data cleaning", "Experiment design", "Reporting"],
    bullets: [
      { label: "Outcome", example: "Built a churn-prediction model that reduced customer churn by 18% year over year." },
      { label: "Scale", example: "Analyzed 50M+ event rows to surface product insights that guided 3 roadmap decisions." },
      { label: "Delivery", example: "Automated weekly reporting for 5 business units, saving 15 hours of manual work per week." },
    ],
    coverTip: "Lead with the business outcome of your models — precision metrics matter less than what changed because of you.",
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    category: "tech",
    summary: "Data analysts collect, clean, and interpret data to guide decisions. Resumes that show dashboards, SQL fluency, and stakeholder impact win interviews.",
    keywords: ["SQL", "Excel", "Power BI", "Tableau", "Python", "Data visualization", "ETL", "Reporting", "KPI tracking", "Statistics"],
    skills: ["Dashboard design", "Data cleaning", "SQL queries", "Storytelling with data", "A/B testing", "Stakeholder communication"],
    bullets: [
      { label: "Impact", example: "Built dashboards used daily by 40+ stakeholders, cutting reporting time from days to minutes." },
      { label: "Insight", example: "Identified pricing inefficiencies that lifted margins by 7% across 3 product lines." },
      { label: "Trust", example: "Owned data quality for 15 reports, reducing reconciliation errors by 90%." },
    ],
    coverTip: "Mention the tools you use daily up front — analyst hiring often filters on SQL, Excel, or BI tool names.",
  },
  {
    id: "cybersecurity-analyst",
    name: "Cybersecurity Analyst",
    category: "tech",
    summary: "Cybersecurity analysts protect systems, data, and users. Resumes should emphasize hands-on defense work, certifications, and security-first thinking.",
    keywords: ["Network security", "SIEM", "Incident response", "Vulnerability assessment", "Firewalls", "SOC", "NIST", "Phishing defense", "Log analysis", "Security audits"],
    skills: ["Threat detection", "Incident handling", "Penetration testing basics", "Risk assessment", "Compliance frameworks", "Security awareness"],
    bullets: [
      { label: "Defense", example: "Monitored and triaged 5,000+ security alerts per week, escalating 200+ real incidents." },
      { label: "Hardening", example: "Led a vulnerability remediation program that reduced critical exposures by 85%." },
      { label: "Awareness", example: "Trained 300+ employees on phishing awareness, cutting click rates by 60%." },
    ],
    coverTip: "List certifications (Security+, CEH, or similar) prominently — they are hard filters in this field.",
  },
  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    category: "tech",
    summary: "DevOps engineers automate infrastructure and deployment. Resumes that show pipelines, cloud platforms, and reliability gains stand out instantly.",
    keywords: ["AWS", "Azure", "GCP", "Docker", "Kubernetes", "Terraform", "CI/CD", "Linux", "Monitoring", "Ansible"],
    skills: ["Infrastructure as code", "Container orchestration", "Pipeline automation", "Cloud cost control", "Incident response", "Observability"],
    bullets: [
      { label: "Automation", example: "Automated deployment pipelines that reduced release time from 4 hours to 12 minutes." },
      { label: "Scale", example: "Managed a 200-node Kubernetes cluster serving 3M+ users with 99.95% uptime." },
      { label: "Efficiency", example: "Cut cloud spend by 35% through rightsizing and workload scheduling." },
    ],
    coverTip: "Quantify uptime, deployments per day, and cost savings — DevOps is measured in reliability and velocity.",
  },
  {
    id: "cloud-engineer",
    name: "Cloud Engineer",
    category: "tech",
    summary: "Cloud engineers design and run infrastructure on platforms like AWS, Azure, and GCP. Resumes with certifications and real architecture wins rank high.",
    keywords: ["AWS", "Azure", "GCP", "IaaS", "PaaS", "Serverless", "Networking", "Storage", "IAM", "Cloud migration"],
    skills: ["Architecture design", "Cost optimization", "Security & IAM", "Migration planning", "Infrastructure automation", "Disaster recovery"],
    bullets: [
      { label: "Migration", example: "Led a 200-server cloud migration with zero downtime and a 25% cost reduction." },
      { label: "Architecture", example: "Designed a serverless architecture that handles 10M+ events per day at near-zero maintenance." },
      { label: "Resilience", example: "Built multi-region failover that kept services online through 3 regional outages." },
    ],
    coverTip: "Name your certifications (AWS Solutions Architect, Azure, etc.) in the first few lines.",
  },
  {
    id: "it-support-specialist",
    name: "IT Support Specialist",
    category: "tech",
    summary: "IT support specialists keep teams running — hardware, software, and users. Resumes that show ticket metrics and happy users get noticed.",
    keywords: ["Help desk", "Troubleshooting", "Windows", "macOS", "Active Directory", "Networking", "Office 365", "Ticketing systems", "Remote support", "Hardware"],
    skills: ["Customer service", "Issue triage", "Asset management", "Documentation", "System administration", "Training users"],
    bullets: [
      { label: "Volume", example: "Resolved 1,200+ support tickets per year with a 95% first-contact resolution rate." },
      { label: "Speed", example: "Cut average response time from 4 hours to 45 minutes with new triage playbooks." },
      { label: "Rollout", example: "Deployed 150+ workstations across 3 offices ahead of schedule." },
    ],
    coverTip: "Show soft skills — empathy and clear communication matter as much as technical fixes in support roles.",
  },
  {
    id: "product-manager",
    name: "Product Manager",
    category: "tech",
    summary: "Product managers own the roadmap between users, design, and engineering. Resumes that show shipped outcomes and clear prioritization stand out.",
    keywords: ["Roadmap", "User research", "Agile", "Scrum", "Stakeholder management", "Analytics", "A/B testing", "Go-to-market", "Backlog", "KPIs"],
    skills: ["Product strategy", "User interviews", "Prioritization", "Data-driven decisions", "Cross-team leadership", "Metrics design"],
    bullets: [
      { label: "Outcome", example: "Shipped a self-serve onboarding flow that lifted activation from 32% to 51%." },
      { label: "Alignment", example: "Aligned 3 teams across 2 quarters to deliver a roadmap with 95% on-time delivery." },
      { label: "Research", example: "Ran 40+ user interviews that redirected the roadmap toward a feature 60% of users now rely on." },
    ],
    coverTip: "Write outcomes, not activities — every bullet should answer 'so what happened for users or revenue?'",
  },
  {
    id: "ai-ml-engineer",
    name: "AI/ML Engineer",
    category: "tech",
    summary: "AI/ML engineers build and deploy intelligent systems. Resumes should show production models, strong fundamentals, and measurable performance gains.",
    keywords: ["Python", "PyTorch", "TensorFlow", "LLMs", "Fine-tuning", "RAG", "MLOps", "Transformers", "Feature engineering", "Model evaluation"],
    skills: ["Model deployment", "Prompt engineering", "ML pipelines", "GPU optimization", "Evaluation frameworks", "API integration"],
    bullets: [
      { label: "Production", example: "Deployed an LLM-based assistant serving 50,000+ queries per day with 94% answer accuracy." },
      { label: "Gain", example: "Fine-tuned a recommendation model that lifted click-through rates by 22%." },
      { label: "Systems", example: "Built an MLOps pipeline that cut model retraining time from days to hours." },
    ],
    coverTip: "Show deployed work — production models beat coursework. A link to a live demo is worth gold.",
  },

  // ── Healthcare (8) ───────────────────────────────────────────────
  {
    id: "registered-nurse",
    name: "Registered Nurse",
    category: "healthcare",
    summary: "Registered nurses deliver patient care across hospitals, clinics, and home settings. Resumes should lead with licenses, clinical experience, and patient outcomes.",
    keywords: ["RN license", "Patient care", "EMR/EHR", "Medication administration", "Care planning", "Vitals monitoring", "BLS/ACLS", "Patient education", "Charting", "Team collaboration"],
    skills: ["Acute care", "Care coordination", "IV therapy", "Wound care", "Patient assessment", "Compassionate communication"],
    bullets: [
      { label: "Care", example: "Managed a 6-patient load per shift in a busy med-surg unit with zero medication errors." },
      { label: "Outcome", example: "Cut patient falls by 30% by implementing hourly rounding on the unit." },
      { label: "Education", example: "Educated 200+ patients and families on discharge plans, improving follow-up compliance." },
    ],
    coverTip: "Lead with your license and certifications — they are the first thing every nursing recruiter scans for.",
  },
  {
    id: "nurse-practitioner",
    name: "Nurse Practitioner",
    category: "healthcare",
    summary: "Nurse practitioners diagnose, treat, and manage patient care with advanced authority. Resumes should showcase scope of practice and measurable patient improvements.",
    keywords: ["NP license", "Patient assessment", "Diagnosis", "Treatment plans", "Prescribing", "Chronic care management", "EMR", "Patient outcomes", "Care coordination", "Preventive care"],
    skills: ["Primary care", "Chronic disease management", "Evidence-based practice", "Patient counseling", "Care team leadership", "Clinical documentation"],
    bullets: [
      { label: "Care", example: "Managed a panel of 900+ patients, achieving 95% follow-up adherence." },
      { label: "Quality", example: "Reduced A1C averages by 1.8 points through a structured diabetes program." },
      { label: "Access", example: "Expanded same-day appointment capacity by 40% with a triage redesign." },
    ],
    coverTip: "Highlight patient panels, chronic-care results, and autonomy — numbers prove your clinical impact.",
  },
  {
    id: "pharmacist",
    name: "Pharmacist",
    category: "healthcare",
    summary: "Pharmacists dispense medication and advise patients and clinicians. Resumes should emphasize accuracy, clinical knowledge, and patient counseling.",
    keywords: ["Pharmacy license", "Medication dispensing", "Drug interactions", "Patient counseling", "Compounding", "Inventory management", "Pharmacy law", "Immunizations", "Clinical review", "Insurance billing"],
    skills: ["Accuracy under pressure", "Drug safety checks", "Patient education", "Inventory control", "Team supervision", "Regulatory compliance"],
    bullets: [
      { label: "Safety", example: "Dispensed 1,500+ prescriptions monthly with a 99.98% accuracy record." },
      { label: "Impact", example: "Introduced a med-reconciliation process that caught 60+ harmful interactions in one year." },
      { label: "Service", example: "Advised 100+ patients weekly on medications and lifestyle, earning a 4.9/5 rating." },
    ],
    coverTip: "List your license and jurisdiction clearly — pharmacists get screened on credentials first.",
  },
  {
    id: "physical-therapist",
    name: "Physical Therapist",
    category: "healthcare",
    summary: "Physical therapists help patients recover movement and strength. Resumes should show caseloads, treatment outcomes, and patient satisfaction.",
    keywords: ["PT license", "Patient assessment", "Treatment plans", "Orthopedics", "Neurological rehab", "Manual therapy", "Documentation", "Rehab programs", "Progress tracking", "Patient education"],
    skills: ["Mobility assessment", "Rehab planning", "Manual therapy", "Exercise prescription", "Progress documentation", "Empathy & coaching"],
    bullets: [
      { label: "Outcome", example: "Returned 85% of post-op knee patients to full function within the expected timeline." },
      { label: "Caseload", example: "Managed 14 patients per day across orthopedic and neurological cases." },
      { label: "Satisfaction", example: "Maintained a 4.8/5 patient satisfaction score over 2 years." },
    ],
    coverTip: "Show outcomes and caseloads — recruiters look for therapists who can handle volume and results.",
  },
  {
    id: "medical-assistant",
    name: "Medical Assistant",
    category: "healthcare",
    summary: "Medical assistants support clinical teams with patient prep, vitals, and administration. Resumes that show both clinical and front-office skill win.",
    keywords: ["Vitals", "Patient intake", "EHR", "Phlebotomy", "Injections", "Scheduling", "Medical billing basics", "HIPAA", "Exam room prep", "Patient communication"],
    skills: ["Patient flow", "Charting", "Phlebotomy", "Immunizations", "Insurance verification", "Team support"],
    bullets: [
      { label: "Flow", example: "Managed intake for 30+ patients per day, keeping clinic wait times under 10 minutes." },
      { label: "Clinical", example: "Performed 100+ blood draws and EKGs per month with zero complications." },
      { label: "Support", example: "Prepped exam rooms and charted 40+ patient encounters daily with 100% HIPAA compliance." },
    ],
    coverTip: "Balance clinical and administrative skills — most clinics want both in one hire.",
  },
  {
    id: "dental-assistant",
    name: "Dental Assistant",
    category: "healthcare",
    summary: "Dental assistants support dentists chairside and manage clinic flow. Resumes should highlight sterilization, chairside skills, and patient comfort.",
    keywords: ["Chairside assisting", "Sterilization", "X-rays", "Patient prep", "Dental charting", "Impressions", "Instrument handling", "Inventory", "HIPAA", "Patient comfort"],
    skills: ["4-handed dentistry", "Radiography", "Infection control", "Patient scheduling", "Billing support", "Team collaboration"],
    bullets: [
      { label: "Chairside", example: "Assisted 15+ patients daily across general, restorative, and orthodontic procedures." },
      { label: "Quality", example: "Maintained 100% infection-control compliance across a 4-chair clinic." },
      { label: "Comfort", example: "Guided anxious patients through procedures, improving on-time starts by 25%." },
    ],
    coverTip: "Mention radiography and sterilization certifications — they are non-negotiable in most practices.",
  },
  {
    id: "lab-technician",
    name: "Laboratory Technician",
    category: "healthcare",
    summary: "Lab technicians run tests and quality control behind the scenes of healthcare. Accuracy and throughput are what employers want to see.",
    keywords: ["Specimen processing", "Hematology", "Microbiology", "Quality control", "Laboratory equipment", "Centrifugation", "Safety protocols", "Data entry", "Sample tracking", "CLIA"],
    skills: ["Precision", "Equipment calibration", "Sterile technique", "Result verification", "Documentation", "Shift reliability"],
    bullets: [
      { label: "Volume", example: "Processed 300+ specimens per shift with zero mislabels." },
      { label: "Quality", example: "Caught 15+ contamination flags that would have skewed patient results." },
      { label: "Compliance", example: "Maintained 100% audit readiness across 3 consecutive inspections." },
    ],
    coverTip: "Highlight accuracy metrics and certifications — this field rewards precision over flair.",
  },
  {
    id: "caregiver",
    name: "Caregiver / CNA",
    category: "healthcare",
    summary: "Caregivers and CNAs provide daily assistance to elderly or disabled clients. Resumes should show trust, reliability, and genuine care.",
    keywords: ["Personal care", "Mobility assistance", "Medication reminders", "Meal preparation", "Housekeeping", "Patient safety", "Documentation", "Companionship", "ADL support", "Care plans"],
    skills: ["Dementia care", "Fall prevention", "Feeding assistance", "Transfers", "Observation & reporting", "Patience & empathy"],
    bullets: [
      { label: "Trust", example: "Cared for 4 elderly clients daily, building long-term trust over 3 years of service." },
      { label: "Safety", example: "Prevented 10+ falls in one year with proactive transfer and mobility support." },
      { label: "Care", example: "Documented daily care notes with 100% accuracy for family and supervisors." },
    ],
    coverTip: "Emphasize reliability and soft skills — families and agencies hire for trust first.",
  },

  // ── Trades & Construction (8) ────────────────────────────────────
  {
    id: "electrician",
    name: "Electrician",
    category: "trades",
    summary: "Electricians install and repair electrical systems in homes, businesses, and sites. Certifications, safety, and project scope drive hiring.",
    keywords: ["Electrical license", "Wiring", "Circuit breakers", "Panel upgrades", "Troubleshooting", "Blueprints", "NEC code", "Safety compliance", "Industrial maintenance", "Residential service"],
    skills: ["Diagnostics", "Code compliance", "Reading schematics", "Preventive maintenance", "Customer communication", "Team work"],
    bullets: [
      { label: "Projects", example: "Completed 120+ residential and commercial installs with zero code violations." },
      { label: "Safety", example: "Maintained a spotless safety record across 5 years of field work." },
      { label: "Speed", example: "Cut average service-call resolution time by 30% with systematic diagnostics." },
    ],
    coverTip: "Put your license number and safety record up top — contractors screen for credentials first.",
  },
  {
    id: "plumber",
    name: "Plumber",
    category: "trades",
    summary: "Plumbers install and repair pipes, fixtures, and water systems. Reliable work history and breadth of skills matter most to employers.",
    keywords: ["Plumbing license", "Pipe installation", "Drain systems", "Water heaters", "Fixture installation", "Leak repair", "Blueprints", "Code compliance", "Commercial plumbing", "Maintenance"],
    skills: ["Diagnostics", "Soldering & fittings", "Backflow prevention", "Emergency repairs", "Customer relations", "Code knowledge"],
    bullets: [
      { label: "Volume", example: "Completed 200+ service and repair calls per year with a 95% first-visit fix rate." },
      { label: "Scope", example: "Installed full water systems for 3 new-build commercial projects." },
      { label: "Quality", example: "Passed 100% of inspections across residential and commercial jobs." },
    ],
    coverTip: "Show breadth — employers pay more for plumbers who handle service, install, and emergency work.",
  },
  {
    id: "carpenter",
    name: "Carpenter",
    category: "trades",
    summary: "Carpenters build and repair structures — framing, finish work, cabinetry. Portfolios and precision projects win the best jobs.",
    keywords: ["Framing", "Finish carpentry", "Trim work", "Cabinetry", "Blueprint reading", "Power tools", "Drywall", "Stairs & railings", "Site safety", "Remodeling"],
    skills: ["Measurement precision", "Material estimation", "Tool mastery", "Restoration work", "Team leadership", "Detail finishing"],
    bullets: [
      { label: "Craft", example: "Delivered custom cabinetry and trim for 25+ luxury home remodels." },
      { label: "Scale", example: "Framed 10+ residential builds from foundation to roof within schedule." },
      { label: "Quality", example: "Held a 0% rework rate across 3 years of finish work." },
    ],
    coverTip: "Attach photos of finished work — carpentry is a visual trade and pictures beat adjectives.",
  },
  {
    id: "welder",
    name: "Welder",
    category: "trades",
    summary: "Welders join metal components across manufacturing, construction, and repair. Certifications and materials experience drive hiring.",
    keywords: ["MIG welding", "TIG welding", "Stick welding", "Flux core", "Blueprints", "Material prep", "Safety protocols", "Quality inspection", "Fabrication", "Stainless steel"],
    skills: ["Precision welds", "Fabrication", "Weld inspection", "Grinding & finishing", "Blueprint reading", "Safety discipline"],
    bullets: [
      { label: "Output", example: "Completed 400+ production welds per week with a 99% pass rate on inspection." },
      { label: "Scope", example: "Welded structural steel across 5 commercial projects in compliance with code." },
      { label: "Quality", example: "Qualified in MIG, TIG, and stick processes across multiple materials." },
    ],
    coverTip: "List every certification and process you're qualified in — they expand which roles you'll be screened for.",
  },
  {
    id: "hvac-technician",
    name: "HVAC Technician",
    category: "trades",
    summary: "HVAC technicians install and service heating, cooling, and ventilation systems. Licenses, refrigerant handling, and troubleshooting skills are key.",
    keywords: ["HVAC license", "Refrigerant handling", "Furnace repair", "AC installation", "Heat pumps", "Ductwork", "Thermostats", "Preventive maintenance", "Diagnostics", "Safety codes"],
    skills: ["System diagnostics", "Load calculations", "Refrigeration", "Preventive care", "Customer education", "Seasonal tuning"],
    bullets: [
      { label: "Calls", example: "Serviced 250+ residential systems per year with a 94% first-visit resolution." },
      { label: "Installs", example: "Installed 80+ heating and cooling systems to manufacturer and code spec." },
      { label: "Quality", example: "Cut emergency-call repeat rate by 40% through thorough preventive checks." },
    ],
    coverTip: "Lead with licenses and refrigerant certification — they are legal requirements in most markets.",
  },
  {
    id: "auto-mechanic",
    name: "Auto Mechanic",
    category: "trades",
    summary: "Auto mechanics diagnose and repair vehicles. Resumes that show brand experience, diagnostics, and customer trust stand out.",
    keywords: ["ASE certification", "Engine repair", "Brake systems", "Diagnostics", "OBD-II", "Electrical systems", "Transmission", "Preventive maintenance", "Shop safety", "Customer service"],
    skills: ["Computer diagnostics", "Engine rebuilds", "Electrical troubleshooting", "Wheel alignment", "Oil changes & services", "Estimating"],
    bullets: [
      { label: "Volume", example: "Completed 40+ repair jobs per week with consistent on-time delivery." },
      { label: "Trust", example: "Built a repeat-customer base of 300+ through honest estimates and clear communication." },
      { label: "Skill", example: "Diagnosed and repaired complex electrical faults that other shops couldn't solve." },
    ],
    coverTip: "List ASE certifications and any manufacturer-specific training — they set you apart instantly.",
  },
  {
    id: "landscaper",
    name: "Landscaper",
    category: "trades",
    summary: "Landscapers design and maintain outdoor spaces. Resumes showing scope of projects, reliability, and equipment skills win commercial accounts.",
    keywords: ["Landscaping", "Lawn care", "Irrigation", "Hardscaping", "Planting", "Sod installation", "Equipment operation", "Seasonal maintenance", "Design", "Customer service"],
    skills: ["Turf management", "Irrigation systems", "Hardscape installation", "Equipment upkeep", "Estimate preparation", "Team coordination"],
    bullets: [
      { label: "Scope", example: "Managed maintenance for 30+ commercial and residential properties." },
      { label: "Build", example: "Designed and installed complete landscapes for 12 new-home builds." },
      { label: "Reliability", example: "Maintained a 100% on-time seasonal schedule across 4 years." },
    ],
    coverTip: "Show both maintenance volume and design/build capability — that combination wins premium clients.",
  },
  {
    id: "construction-laborer",
    name: "Construction Laborer",
    category: "trades",
    summary: "Construction laborers support crews with site prep, materials, and cleanup. Reliability, safety training, and versatility drive hiring.",
    keywords: ["Site prep", "Material handling", "Demolition", "Concrete work", "Framing support", "Cleanup", "Safety training", "Equipment use", "Teamwork", "OSHA"],
    skills: ["Physical stamina", "Tool familiarity", "Site safety", "Concrete pouring", "Loading & unloading", "Follow-through"],
    bullets: [
      { label: "Support", example: "Supported 3 crews across residential builds, keeping sites job-ready daily." },
      { label: "Safety", example: "Maintained zero injuries across 3 years of field work." },
      { label: "Versatility", example: "Cross-trained in concrete, demolition, and finishing support roles." },
    ],
    coverTip: "List safety training and certifications — they move you to the top of the hiring list.",
  },

  // ── Business & Finance (9) ───────────────────────────────────────
  {
    id: "accountant",
    name: "Accountant",
    category: "business",
    summary: "Accountants manage books, taxes, and compliance. Certifications, software fluency, and clean client work are what hiring managers scan for.",
    keywords: ["CPA", "Bookkeeping", "Accounts payable/receivable", "Tax preparation", "Financial statements", "GAAP", "QuickBooks", "Excel", "Audit support", "Reconciliation"],
    skills: ["General ledger", "Payroll", "Tax compliance", "Month-end close", "Audit readiness", "Client advisory"],
    bullets: [
      { label: "Books", example: "Managed full-cycle accounting for 40+ small-business clients." },
      { label: "Compliance", example: "Prepared 200+ tax returns with a 100% accuracy record across 3 seasons." },
      { label: "Speed", example: "Cut month-end close from 8 days to 3 through workflow improvements." },
    ],
    coverTip: "Lead with your designation and software stack — both are hard filters in accounting hiring.",
  },
  {
    id: "financial-analyst",
    name: "Financial Analyst",
    category: "business",
    summary: "Financial analysts model performance and guide decisions. Resumes should show modeling skills, analysis depth, and decision impact.",
    keywords: ["Financial modeling", "Forecasting", "Excel", "Power BI", "SQL", "Variance analysis", "Budgeting", "Valuation", "KPI reporting", "FP&A"],
    skills: ["3-statement modeling", "Scenario analysis", "Data visualization", "Business partnering", "Due diligence", "Presentation skills"],
    bullets: [
      { label: "Insight", example: "Built a forecasting model that improved budget accuracy by 25%." },
      { label: "Impact", example: "Identified $1.2M in cost savings through variance analysis across 4 business units." },
      { label: "Reporting", example: "Delivered monthly board-level reporting for a $50M portfolio." },
    ],
    coverTip: "Show the decisions your analysis influenced — impact beats tool lists in this role.",
  },
  {
    id: "marketing-manager",
    name: "Marketing Manager",
    category: "business",
    summary: "Marketing managers own campaigns, channels, and growth. Resumes that show ROI, channel mastery, and team leadership win interviews.",
    keywords: ["Campaign management", "SEO", "Content marketing", "Paid ads", "Email marketing", "Social media", "Analytics", "Budget management", "A/B testing", "Brand strategy"],
    skills: ["Growth strategy", "Channel optimization", "Team leadership", "Reporting & analytics", "Copywriting", "Vendor management"],
    bullets: [
      { label: "Growth", example: "Grew organic traffic by 180% in 12 months through SEO and content strategy." },
      { label: "ROI", example: "Managed a $200K ad budget at a 3.5x average return." },
      { label: "Team", example: "Led a 4-person marketing team across 6 launches with on-time delivery." },
    ],
    coverTip: "Open with one big growth number — marketing hiring managers skim for ROI proof.",
  },
  {
    id: "sales-representative",
    name: "Sales Representative",
    category: "business",
    summary: "Sales representatives own pipelines and quotas. Numbers — quotas hit, deals closed, revenue won — are the entire resume.",
    keywords: ["Quota attainment", "Pipeline management", "CRM", "Cold outreach", "Negotiation", "B2B sales", "Lead generation", "Upselling", "Forecasting", "Proposals"],
    skills: ["Closing", "Relationship building", "Objection handling", "Product demos", "Territory planning", "Reporting discipline"],
    bullets: [
      { label: "Quota", example: "Exceeded annual quota by 130% for 3 consecutive years." },
      { label: "Revenue", example: "Closed $1.5M in new business across 40+ enterprise accounts." },
      { label: "Pipeline", example: "Built a 3x coverage pipeline through consistent outbound activity." },
    ],
    coverTip: "Every bullet should contain a number — sales is the most metric-driven resume on the market.",
  },
  {
    id: "hr-manager",
    name: "HR Manager",
    category: "business",
    summary: "HR managers own people operations — hiring, culture, compliance. Resumes showing measurable hiring and retention wins stand out.",
    keywords: ["Recruiting", "Onboarding", "Employee relations", "Performance management", "HRIS", "Payroll", "Compliance", "Benefits", "Retention", "Policy development"],
    skills: ["Talent acquisition", "Conflict resolution", "Training programs", "Data & reporting", "Labor law", "Culture building"],
    bullets: [
      { label: "Hiring", example: "Scaled headcount from 40 to 120 while cutting time-to-hire by 30%." },
      { label: "Retention", example: "Raised 12-month retention from 70% to 89% with new onboarding and engagement programs." },
      { label: "Compliance", example: "Led the company through 3 successful audits with zero findings." },
    ],
    coverTip: "Show people metrics — hiring speed, retention, and engagement beat process lists.",
  },
  {
    id: "project-manager",
    name: "Project Manager",
    category: "business",
    summary: "Project managers deliver work on time and on budget. Resumes should show project scope, methodology, and delivery results.",
    keywords: ["Project planning", "Agile", "Scrum", "PMI/PMP", "Budget management", "Stakeholder communication", "Risk management", "Timelines", "Reporting", "Resource allocation"],
    skills: ["Scope control", "Cross-functional leadership", "Risk mitigation", "Vendor management", "Milestone tracking", "Client communication"],
    bullets: [
      { label: "Delivery", example: "Delivered 15+ projects on time and on budget across 3 years." },
      { label: "Scale", example: "Managed a $2M program with 8 stakeholders across 3 countries." },
      { label: "Efficiency", example: "Cut project cycle time by 25% through better planning and reporting." },
    ],
    coverTip: "Lead with scale and delivery stats — budget, team size, and on-time rate are your proof.",
  },
  {
    id: "operations-manager",
    name: "Operations Manager",
    category: "business",
    summary: "Operations managers run the day-to-day machinery of a business. Efficiency gains, cost control, and process wins define strong resumes.",
    keywords: ["Process improvement", "Cost reduction", "Supply chain", "Inventory management", "Team management", "KPIs", "Vendor negotiation", "Quality control", "SOPs", "Logistics"],
    skills: ["Lean operations", "Vendor management", "Data-driven decisions", "Team leadership", "Facility management", "Continuous improvement"],
    bullets: [
      { label: "Efficiency", example: "Cut operating costs by 18% through vendor renegotiation and process redesign." },
      { label: "Scale", example: "Managed daily operations for a 50-person team across 2 sites." },
      { label: "Quality", example: "Reduced order errors from 4% to 0.5% with new quality checkpoints." },
    ],
    coverTip: "Quantify cost and efficiency — operations hiring is about the money you save and the flow you improve.",
  },
  {
    id: "administrative-assistant",
    name: "Administrative Assistant",
    category: "business",
    summary: "Administrative assistants keep offices running — calendars, communication, and coordination. Reliability and organizational wins carry the resume.",
    keywords: ["Scheduling", "Calendar management", "Email management", "Office tools", "Travel arrangements", "Record keeping", "Meeting coordination", "Customer service", "Data entry", "Procurement"],
    skills: ["Organization", "Communication", "Discretion", "Multitasking", "Software fluency", "Process support"],
    bullets: [
      { label: "Support", example: "Managed calendars and travel for 4 executives, coordinating 300+ meetings yearly." },
      { label: "Systems", example: "Digitized filing and scheduling, saving the office 8 hours per week." },
      { label: "Service", example: "Served as first point of contact for 50+ daily visitors and calls." },
    ],
    coverTip: "Show systems you improved — assistants who build order beat assistants who only react.",
  },
  {
    id: "recruiter",
    name: "Recruiter",
    category: "business",
    summary: "Recruiters find and close talent. Time-to-fill, placement volume, and offer-acceptance rates are the numbers that matter.",
    keywords: ["Sourcing", "Screening", "Interviews", "Offer negotiation", "ATS", "Boolean search", "Talent pipelines", "LinkedIn recruiting", "Time-to-fill", "Diversity hiring"],
    skills: ["Sourcing strategy", "Candidate experience", "Stakeholder partnership", "Offer closing", "Market research", "Reporting"],
    bullets: [
      { label: "Volume", example: "Filled 120+ roles per year across engineering, sales, and operations." },
      { label: "Speed", example: "Cut average time-to-fill from 45 to 28 days with better sourcing funnels." },
      { label: "Quality", example: "Reached 95% offer acceptance through transparent candidate communication." },
    ],
    coverTip: "Quantify fills, time-to-fill, and acceptance rates — those are the three numbers recruiters are judged on.",
  },

  // ── Education (4) ─────────────────────────────────────────────────
  {
    id: "high-school-teacher",
    name: "High School Teacher",
    category: "education",
    summary: "High school teachers plan lessons, teach subjects, and guide students. Certifications, subject expertise, and student results anchor the resume.",
    keywords: ["Teaching license", "Lesson planning", "Classroom management", "Curriculum development", "Student assessment", "Differentiated instruction", "Parent communication", "Extracurriculars", "Special education support", "Technology in the classroom"],
    skills: ["Subject expertise", "Engagement strategies", "Grading & feedback", "Behavior management", "Mentoring", "Communication"],
    bullets: [
      { label: "Results", example: "Raised average exam pass rates from 78% to 91% in two years." },
      { label: "Leadership", example: "Advised the STEM club, growing participation from 15 to 80 students." },
      { label: "Care", example: "Built parent partnerships through structured updates for 150+ students yearly." },
    ],
    coverTip: "Show student outcomes and initiatives — schools hire teachers who improve results, not just teach classes.",
  },
  {
    id: "elementary-teacher",
    name: "Elementary School Teacher",
    category: "education",
    summary: "Elementary teachers build foundations across reading, math, and life skills. Warmth, classroom management, and measurable progress matter.",
    keywords: ["Teaching license", "Literacy instruction", "Math foundations", "Classroom management", "Lesson planning", "Differentiated instruction", "Student progress tracking", "Parent engagement", "Social-emotional learning", "Assessment"],
    skills: ["Early literacy", "Behavior support", "Creative lessons", "Progress reporting", "Inclusion", "Patience & empathy"],
    bullets: [
      { label: "Growth", example: "Lifted class reading proficiency by 25% through targeted small-group instruction." },
      { label: "Culture", example: "Built a positive classroom community with a 0% referral year." },
      { label: "Partnership", example: "Engaged 100% of families through monthly progress communications." },
    ],
    coverTip: "Show growth in literacy and numeracy — those are the outcomes parents and principals care about.",
  },
  {
    id: "teaching-assistant",
    name: "Teaching Assistant",
    category: "education",
    summary: "Teaching assistants support teachers and students in the classroom. Reliability, patience, and student support stories define the resume.",
    keywords: ["Classroom support", "Small group instruction", "Student supervision", "Lesson prep", "Individualized support", "Behavior support", "Special education", "Record keeping", "Communication", "Inclusion"],
    skills: ["Student support", "Adaptability", "Patience", "Coordination", "Literacy support", "Team collaboration"],
    bullets: [
      { label: "Support", example: "Provided one-on-one and small-group support to 15+ students daily." },
      { label: "Growth", example: "Helped 10 struggling readers advance 2 grade levels in one year." },
      { label: "Team", example: "Prepared materials and managed classroom flow for 4 teachers." },
    ],
    coverTip: "Show specific support wins — assistants who move student outcomes get moved to permanent positions.",
  },
  {
    id: "tutor",
    name: "Tutor",
    category: "education",
    summary: "Tutors deliver focused academic help across subjects. Results, subjects, and student relationships make the resume.",
    keywords: ["Subject tutoring", "Exam prep", "Lesson planning", "Student assessment", "Progress tracking", "Homework support", "Online tutoring", "Communication with parents", "Learning styles", "Motivation"],
    skills: ["Subject mastery", "Explanation clarity", "Patience", "Progress tracking", "Adaptive teaching", "Rapport building"],
    bullets: [
      { label: "Results", example: "Raised student grades by an average of 2 letter grades within 3 months." },
      { label: "Scale", example: "Tutored 20+ students weekly across math, science, and exam prep." },
      { label: "Trust", example: "Retained 90% of students semester over semester through strong results." },
    ],
    coverTip: "Lead with grade improvements and retention — families re-hire tutors who prove outcomes.",
  },

  // ── Creative & Media (6) ─────────────────────────────────────────
  {
    id: "graphic-designer",
    name: "Graphic Designer",
    category: "creative",
    summary: "Graphic designers create visual identities, marketing, and print. A portfolio is the resume — this document should drive people to it.",
    keywords: ["Adobe Photoshop", "Illustrator", "InDesign", "Brand identity", "Typography", "Layout design", "Print production", "Social media graphics", "Color theory", "Figma"],
    skills: ["Brand systems", "Editorial layout", "Print-ready files", "Packaging", "Client presentations", "Art direction"],
    bullets: [
      { label: "Brand", example: "Designed complete brand identities for 15+ companies." },
      { label: "Scale", example: "Produced 300+ marketing assets per quarter across print and digital." },
      { label: "Impact", example: "Redesigned a client's packaging, lifting retail shelf recognition in-store." },
    ],
    coverTip: "Link your portfolio in the first line — recruiters judge designers by work, not words.",
  },
  {
    id: "ux-ui-designer",
    name: "UX/UI Designer",
    category: "creative",
    summary: "UX/UI designers shape how products feel and work. Case studies, process, and measurable improvements drive hiring decisions.",
    keywords: ["User research", "Wireframes", "Prototyping", "Figma", "Usability testing", "Design systems", "Interaction design", "Accessibility", "Information architecture", "Mobile design"],
    skills: ["User flows", "Prototyping", "Usability testing", "Design systems", "Collaboration with engineers", "Data-informed design"],
    bullets: [
      { label: "Research", example: "Ran 25+ usability sessions that cut checkout drop-off by 30%." },
      { label: "Systems", example: "Built a design system adopted across 40+ screens and 5 products." },
      { label: "Impact", example: "Redesigned onboarding, lifting activation rates from 35% to 58%." },
    ],
    coverTip: "Include 2-3 case studies with outcomes — UX hiring is decided on process and results, not decoration.",
  },
  {
    id: "content-writer",
    name: "Content Writer",
    category: "creative",
    summary: "Content writers create articles, blogs, and marketing copy. Published work, niches, and traffic results carry the resume.",
    keywords: ["SEO writing", "Blog posts", "Copywriting", "Editing", "Content strategy", "Research", "CMS", "Web content", "Social media copy", "Brand voice"],
    skills: ["SEO optimization", "Clear structuring", "Research depth", "Editing & proofing", "Niche expertise", "Deadline discipline"],
    bullets: [
      { label: "Traffic", example: "Wrote 100+ SEO articles that drove 2M+ organic visits in 18 months." },
      { label: "Scale", example: "Produced 20+ pieces monthly across 6 client brands." },
      { label: "Rankings", example: "Ranked 40+ articles in the top 3 Google results for target keywords." },
    ],
    coverTip: "Show published links and traffic numbers — samples plus proof of results are the whole game.",
  },
  {
    id: "social-media-manager",
    name: "Social Media Manager",
    category: "creative",
    summary: "Social media managers grow audiences and engagement across platforms. Growth numbers and campaign wins define the resume.",
    keywords: ["Content calendars", "Instagram", "TikTok", "LinkedIn", "YouTube", "Community management", "Paid social", "Analytics", "Influencer partnerships", "Brand voice"],
    skills: ["Content strategy", "Reels & short video", "Community engagement", "Analytics reporting", "Campaign planning", "Trend awareness"],
    bullets: [
      { label: "Growth", example: "Grew a brand's following from 10K to 150K in 14 months." },
      { label: "Engagement", example: "Lifted average engagement rate from 1.2% to 4.8%." },
      { label: "Campaigns", example: "Ran campaigns that drove 300K+ views and 12K link clicks per quarter." },
    ],
    coverTip: "Open with growth numbers — follower counts, engagement rates, and views are the universal language here.",
  },
  {
    id: "video-editor",
    name: "Video Editor",
    category: "creative",
    summary: "Video editors cut, color, and finish video content. Showreels, tools, and throughput make the resume effective.",
    keywords: ["Adobe Premiere Pro", "Final Cut Pro", "DaVinci Resolve", "Motion graphics", "Color grading", "Audio mixing", "Storytelling", "Short-form video", "Titles & graphics", "Deliverables"],
    skills: ["Narrative cutting", "Color correction", "Sound design", "Motion graphics", "Efficient workflows", "Client revisions"],
    bullets: [
      { label: "Volume", example: "Delivered 40+ videos per month for creators and brands." },
      { label: "Views", example: "Edited content that accumulated 50M+ views across platforms." },
      { label: "Speed", example: "Turned around 10-minute edits in under 24 hours on tight deadlines." },
    ],
    coverTip: "Link your showreel first — editors are hired on 60 seconds of footage, not six lines of text.",
  },
  {
    id: "photographer",
    name: "Photographer",
    category: "creative",
    summary: "Photographers capture portraits, events, and commercial work. Portfolios and client experience anchor the resume.",
    keywords: ["Portrait photography", "Event photography", "Commercial shoots", "Editing (Lightroom)", "Photoshop", "Lighting setup", "Client delivery", "Studio work", "Location shoots", "Retouching"],
    skills: ["Lighting mastery", "Composition", "Retouching", "Client direction", "Fast delivery", "Equipment care"],
    bullets: [
      { label: "Clientele", example: "Shot 100+ sessions per year for families, brands, and events." },
      { label: "Revenue", example: "Built a 90% repeat-and-referral client base." },
      { label: "Delivery", example: "Delivered fully edited galleries within 5 days, exceeding client expectations." },
    ],
    coverTip: "Gallery link up top and client types in bullets — commercial work out-earns hobby shoots in every market.",
  },

  // ── Hospitality & Retail (6) ─────────────────────────────────────
  {
    id: "chef",
    name: "Chef",
    category: "hospitality",
    summary: "Chefs run kitchens — menus, teams, and quality. Resume strength comes from cuisine range, kitchen scale, and consistency.",
    keywords: ["Menu development", "Kitchen management", "Food safety", "Cost control", "Inventory", "Team supervision", "Garde manger", "Line cooking", "Fine dining", "Prep systems"],
    skills: ["Cuisine range", "Cost & portioning", "Staff training", "Sanitation standards", "Menu costing", "Consistency under pressure"],
    bullets: [
      { label: "Kitchen", example: "Ran a 12-person kitchen serving 400+ covers daily." },
      { label: "Costs", example: "Cut food cost from 34% to 28% through menu and portioning changes." },
      { label: "Quality", example: "Launched a new menu that lifted guest satisfaction scores by 20%." },
    ],
    coverTip: "Show kitchen scale and cost control — owners hire chefs who run kitchens, not just cook in them.",
  },
  {
    id: "restaurant-server",
    name: "Restaurant Server",
    category: "hospitality",
    summary: "Servers own the guest experience — speed, accuracy, and upsells. Tips, tables, and consistency make the resume.",
    keywords: ["Table service", "POS systems", "Upselling", "Food & beverage knowledge", "Guest relations", "Cash handling", "Team coordination", "Allergy awareness", "High-volume service", "Opening/closing duties"],
    skills: ["Speed & accuracy", "Guest warmth", "Menu knowledge", "Complaint recovery", "Section management", "Teamwork"],
    bullets: [
      { label: "Service", example: "Served 30+ tables per shift in a high-volume restaurant." },
      { label: "Sales", example: "Consistently topped the team in dessert and wine upsells." },
      { label: "Quality", example: "Earned recognition for 100% guest satisfaction over 6 months." },
    ],
    coverTip: "Mention high-volume experience and specialty training — they signal readiness for premium venues.",
  },
  {
    id: "barista",
    name: "Barista",
    category: "hospitality",
    summary: "Baristas craft drinks and build the café experience. Speed, latte art, and service warmth define the resume.",
    keywords: ["Espresso drinks", "Latte art", "POS", "Customer service", "Coffee knowledge", "Inventory", "Cleanliness standards", "Team shifts", "Cash handling", "Café operations"],
    skills: ["Drink consistency", "Speed & multitasking", "Coffee knowledge", "Guest warmth", "Opening/closing", "Stock rotation"],
    bullets: [
      { label: "Speed", example: "Crafted 200+ drinks per shift during peak hours without losing quality." },
      { label: "Service", example: "Built a loyal regular base that grew café sales by 15%." },
      { label: "Skill", example: "Trained 6 new baristas on espresso standards and latte art." },
    ],
    coverTip: "Show speed numbers and training experience — specialty cafés hire baristas who raise the bar.",
  },
  {
    id: "hotel-front-desk-agent",
    name: "Hotel Front Desk Agent",
    category: "hospitality",
    summary: "Front desk agents are the face of hotels — check-ins, reservations, and guest care. Service scores and upsells carry the resume.",
    keywords: ["Check-in/check-out", "Reservations", "PMS", "Guest relations", "Upselling", "Concierge services", "Cash handling", "Group bookings", "Guest satisfaction", "Phone etiquette"],
    skills: ["Warm service", "Problem solving", "System fluency", "Room upsells", "Multitasking", "Composure under pressure"],
    bullets: [
      { label: "Service", example: "Checked in 100+ guests per shift with a 4.9/5 satisfaction rating." },
      { label: "Revenue", example: "Lifted room upsells by 20% through personalized guest conversations." },
      { label: "Quality", example: "Resolved 30+ guest issues monthly, most within minutes." },
    ],
    coverTip: "Lead with satisfaction scores and upsell results — hotels hire the front desk to drive both.",
  },
  {
    id: "retail-sales-associate",
    name: "Retail Sales Associate",
    category: "hospitality",
    summary: "Retail associates move products and build customer loyalty. Sales numbers, service, and store standards matter most.",
    keywords: ["Customer service", "POS", "Merchandising", "Inventory", "Upselling", "Store displays", "Returns & exchanges", "Loss prevention", "Product knowledge", "Team sales goals"],
    skills: ["Customer connection", "Product knowledge", "Visual merchandising", "Stock control", "Speed & tidiness", "Sales conversation"],
    bullets: [
      { label: "Sales", example: "Beat monthly sales targets by 15% on average." },
      { label: "Loyalty", example: "Converted 30+ new loyalty members monthly through genuine service." },
      { label: "Standards", example: "Maintained a spotless, well-merchandised floor rated top in region." },
    ],
    coverTip: "Numbers beat adjectives — target attainment and loyalty signups prove you can sell.",
  },
  {
    id: "store-manager",
    name: "Store Manager",
    category: "hospitality",
    summary: "Store managers run P&L, teams, and operations. Sales growth, team stability, and inventory control are the story.",
    keywords: ["P&L management", "Sales targets", "Team leadership", "Inventory control", "Staff scheduling", "Customer service standards", "Loss prevention", "Merchandising", "Training & development", "Reporting"],
    skills: ["Sales leadership", "Team building", "Inventory accuracy", "Schedule management", "Compliance", "Vendor relations"],
    bullets: [
      { label: "Growth", example: "Grew store revenue 22% year over year while holding costs flat." },
      { label: "Team", example: "Cut staff turnover from 60% to 25% with structured training." },
      { label: "Control", example: "Reduced inventory shrinkage to 0.4%, well below district average." },
    ],
    coverTip: "Show P&L-style wins — revenue, shrinkage, and turnover are the three numbers district leaders read first.",
  },

  // ── Logistics, Legal & Other (7) ─────────────────────────────────
  {
    id: "paralegal",
    name: "Paralegal",
    category: "other",
    summary: "Paralegals support attorneys with research, drafting, and case management. Precision, practice areas, and volume of work define the resume.",
    keywords: ["Legal research", "Document drafting", "Case management", "Discovery", "E-filing", "Contracts", "Due diligence", "Client intake", "Trial prep", "Confidentiality"],
    skills: ["Research precision", "Drafting", "Deadline discipline", "Case organization", "Client communication", "Software fluency"],
    bullets: [
      { label: "Volume", example: "Managed 30+ active cases, keeping every deadline met for 2 years." },
      { label: "Drafting", example: "Drafted 500+ pleadings, contracts, and discovery documents." },
      { label: "Trials", example: "Prepared trial binders for 12 cases, contributing to 9 favorable outcomes." },
    ],
    coverTip: "Name your practice areas and case volume — firms hire paralegals who can carry a caseload.",
  },
  {
    id: "truck-driver",
    name: "Truck Driver",
    category: "other",
    summary: "Truck drivers move freight safely and on time. License class, safety record, and miles matter most.",
    keywords: ["CDL", "Long-haul", "Local delivery", "Hazmat", "Tanker endorsement", "Load securement", "ELD compliance", "Route planning", "Safety record", "DOT regulations"],
    skills: ["Defensive driving", "Load securement", "Log compliance", "Route efficiency", "Vehicle inspections", "Reliability"],
    bullets: [
      { label: "Miles", example: "Logged 120,000+ accident-free miles over 3 years." },
      { label: "Delivery", example: "Maintained a 99% on-time delivery rate across regional routes." },
      { label: "Compliance", example: "Passed 100% of DOT inspections and drug screenings." },
    ],
    coverTip: "Lead with your license class, endorsements, and clean safety record — they are non-negotiable filters.",
  },
  {
    id: "warehouse-associate",
    name: "Warehouse Associate",
    category: "other",
    summary: "Warehouse associates pick, pack, and ship orders. Accuracy, speed, and equipment skills carry the resume.",
    keywords: ["Order picking", "Packing", "Shipping & receiving", "Forklift", "RF scanning", "Inventory counts", "Safety protocols", "Loading docks", "Returns processing", "Labels"],
    skills: ["Speed & accuracy", "RF scanner fluency", "Forklift operation", "Stock organization", "Team coordination", "Safety discipline"],
    bullets: [
      { label: "Volume", example: "Picked and packed 300+ orders per shift with 99.9% accuracy." },
      { label: "Equipment", example: "Operated forklifts and pallet jacks safely across 2 facilities." },
      { label: "Improvement", example: "Helped redesign the pick path, cutting walking time by 20%." },
    ],
    coverTip: "Show accuracy rates and equipment certifications — both move you up the hiring list fast.",
  },
  {
    id: "flight-attendant",
    name: "Flight Attendant",
    category: "other",
    summary: "Flight attendants ensure safety and service at 35,000 feet. Service experience, languages, and certifications matter.",
    keywords: ["Safety procedures", "In-flight service", "Customer care", "Emergency training", "First aid", "Language skills", "Crew coordination", "Grooming standards", "Conflict resolution", "Passenger assistance"],
    skills: ["Calm under pressure", "Service excellence", "Language fluency", "Safety awareness", "Team coordination", "Flexibility"],
    bullets: [
      { label: "Service", example: "Served 150+ passengers per flight with a consistent 5-star rating." },
      { label: "Safety", example: "Completed rigorous emergency and first-aid training with top scores." },
      { label: "Languages", example: "Served passengers in 3 languages, including international routes." },
    ],
    coverTip: "Highlight language fluency and service volume — both are screens in airline hiring.",
  },
  {
    id: "security-officer",
    name: "Security Officer",
    category: "other",
    summary: "Security officers protect people and property. Licenses, vigilance, and incident handling define the resume.",
    keywords: ["Surveillance", "Patrols", "Access control", "Incident reports", "CCTV monitoring", "Emergency response", "Guest screening", "De-escalation", "Site safety", "License/guard card"],
    skills: ["Vigilance", "Report writing", "De-escalation", "Access management", "Emergency procedures", "Customer-friendly presence"],
    bullets: [
      { label: "Vigilance", example: "Monitored CCTV across 40+ camera feeds with zero missed incidents." },
      { label: "Reports", example: "Documented 500+ incident and shift reports with full accuracy." },
      { label: "Safety", example: "Responded to 20+ alarms and emergencies, keeping sites fully protected." },
    ],
    coverTip: "List your guard license and reporting discipline — documented vigilance is what clients pay for.",
  },
  {
    id: "customer-service-representative",
    name: "Customer Service Representative",
    category: "other",
    summary: "CSRs handle customer questions, issues, and retention. Resolution rates, speed, and satisfaction scores carry the resume.",
    keywords: ["Support tickets", "Phone support", "Live chat", "CRM", "Complaint resolution", "Product knowledge", "SLA adherence", "Customer retention", "Escalation handling", "Documentation"],
    skills: ["Clear communication", "Problem solving", "Empathy", "Fast typing", "CRM fluency", "De-escalation"],
    bullets: [
      { label: "Volume", example: "Resolved 80+ customer issues per day across phone and chat." },
      { label: "Quality", example: "Maintained a 95% satisfaction rating and a 4.8/5 CSAT score." },
      { label: "Retention", example: "Saved 200+ at-risk accounts through effective retention conversations." },
    ],
    coverTip: "Show CSAT and resolution volume — those two numbers decide call-center hiring.",
  },
  {
    id: "real-estate-agent",
    name: "Real Estate Agent",
    category: "other",
    summary: "Real estate agents buy, sell, and list properties. Volume, revenue, and market knowledge make the resume.",
    keywords: ["Residential sales", "Listings", "Buyer representation", "Contracts", "Market analysis", "Open houses", "Negotiation", "Lead generation", "Client acquisition", "MLS"],
    skills: ["Negotiation", "Lead generation", "Market knowledge", "Marketing properties", "Contract handling", "Client relationships"],
    bullets: [
      { label: "Volume", example: "Closed 25+ transactions per year across residential markets." },
      { label: "Revenue", example: "Generated $8M+ in annual sales volume for 3 consecutive years." },
      { label: "Growth", example: "Grew a client base from referrals to 60% repeat business." },
    ],
    coverTip: "Lead with closed deals and sales volume — the industry runs on production numbers.",
  },
];

export function getJob(id: string): Job | undefined {
  return JOBS.find((job) => job.id === id);
}

export function jobSlug(job: Job): string {
  return job.id;
}