export type City = {
  name: string;
  country: string;
  region: string;
  pop: string;
  industries: string[];
  landmarks: string[];
  districts: string[];
  university: string;
};

export const REGION_LABELS: Record<string, string> = {
  usa: "United States",
  canada: "Canada",
  "uk-ireland": "United Kingdom & Ireland",
  europe: "Europe",
  australasia: "Australia & New Zealand",
  "asia-middleeast": "Asia & Middle East",
  africa: "Africa",
  latam: "Latin America",
};

export const CITIES: City[] = [
  // ── United States (30) ─────────────────────────────────────────────
  { name: "New York", country: "United States", region: "usa", pop: "~8.8 million", industries: ["finance", "media", "technology"], landmarks: ["the Empire State Building", "Central Park"], districts: ["Manhattan", "Brooklyn"], university: "Columbia University" },
  { name: "Los Angeles", country: "United States", region: "usa", pop: "~3.9 million", industries: ["entertainment", "technology", "startups"], landmarks: ["the Hollywood Sign", "Santa Monica Pier"], districts: ["Hollywood", "Downtown LA"], university: "UCLA" },
  { name: "Chicago", country: "United States", region: "usa", pop: "~2.7 million", industries: ["finance", "logistics", "manufacturing"], landmarks: ["the Willis Tower", "Millennium Park"], districts: ["The Loop", "River North"], university: "University of Chicago" },
  { name: "Houston", country: "United States", region: "usa", pop: "~2.3 million", industries: ["energy", "healthcare", "aerospace"], landmarks: ["Space Center Houston", "the Houston Museum District"], districts: ["Uptown", "Midtown"], university: "Rice University" },
  { name: "Phoenix", country: "United States", region: "usa", pop: "~1.6 million", industries: ["technology", "real estate", "finance"], landmarks: ["Camelback Mountain", "the Desert Botanical Garden"], districts: ["Downtown Phoenix", "Scottsdale"], university: "Arizona State University" },
  { name: "Philadelphia", country: "United States", region: "usa", pop: "~1.6 million", industries: ["healthcare", "education", "pharmaceuticals"], landmarks: ["the Liberty Bell", "Independence Hall"], districts: ["Center City", "University City"], university: "University of Pennsylvania" },
  { name: "San Diego", country: "United States", region: "usa", pop: "~1.4 million", industries: ["biotech", "defense", "tourism"], landmarks: ["Balboa Park", "the USS Midway Museum"], districts: ["Gaslamp Quarter", "La Jolla"], university: "UC San Diego" },
  { name: "Dallas", country: "United States", region: "usa", pop: "~1.3 million", industries: ["banking", "telecommunications", "real estate"], landmarks: ["Reunion Tower", "the Dallas Arts District"], districts: ["Uptown", "Deep Ellum"], university: "Southern Methodist University" },
  { name: "San Jose", country: "United States", region: "usa", pop: "~1.0 million", industries: ["semiconductors", "software", "AI research"], landmarks: ["the Winchester Mystery House", "Almaden Quicksilver County Park"], districts: ["Downtown San Jose", "Santana Row"], university: "San Jose State University" },
  { name: "Austin", country: "United States", region: "usa", pop: "~0.97 million", industries: ["technology", "music", "fintech"], landmarks: ["the Texas State Capitol", "Zilker Park"], districts: ["Downtown Austin", "South Congress"], university: "University of Texas at Austin" },
  { name: "Charlotte", country: "United States", region: "usa", pop: "~0.87 million", industries: ["banking", "fintech", "energy"], landmarks: ["the NASCAR Hall of Fame", "Carowinds"], districts: ["Uptown", "South End"], university: "UNC Charlotte" },
  { name: "San Francisco", country: "United States", region: "usa", pop: "~0.81 million", industries: ["software", "AI", "fintech"], landmarks: ["the Golden Gate Bridge", "Alcatraz Island"], districts: ["SoMa", "the Mission District"], university: "Stanford University" },
  { name: "Indianapolis", country: "United States", region: "usa", pop: "~0.88 million", industries: ["motorsports", "healthcare", "logistics"], landmarks: ["the Indianapolis Motor Speedway", "White River State Park"], districts: ["Downtown Indianapolis", "Broad Ripple"], university: "Indiana University–Purdue University Indianapolis" },
  { name: "Seattle", country: "United States", region: "usa", pop: "~0.73 million", industries: ["technology", "biotech", "aerospace"], landmarks: ["the Space Needle", "Pike Place Market"], districts: ["Belltown", "Capitol Hill"], university: "University of Washington" },
  { name: "Denver", country: "United States", region: "usa", pop: "~0.72 million", industries: ["technology", "energy", "aerospace"], landmarks: ["the Rocky Mountain foothills", "Union Station"], districts: ["LoDo", "RiNo"], university: "University of Colorado Denver" },
  { name: "Washington", country: "United States", region: "usa", pop: "~0.69 million", industries: ["government", "consulting", "nonprofits"], landmarks: ["the White House", "the National Mall"], districts: ["Georgetown", "Capitol Hill"], university: "Georgetown University" },
  { name: "Boston", country: "United States", region: "usa", pop: "~0.65 million", industries: ["biotech", "education", "finance"], landmarks: ["Freedom Trail", "Fenway Park"], districts: ["Back Bay", "Seaport"], university: "MIT" },
  { name: "Nashville", country: "United States", region: "usa", pop: "~0.69 million", industries: ["music", "healthcare", "tourism"], landmarks: ["the Ryman Auditorium", "the Grand Ole Opry"], districts: ["Downtown Nashville", "the Gulch"], university: "Vanderbilt University" },
  { name: "Detroit", country: "United States", region: "usa", pop: "~0.63 million", industries: ["automotive", "manufacturing", "mobility"], landmarks: ["the Detroit Institute of Arts", "the Renaissance Center"], districts: ["Downtown Detroit", "Corktown"], university: "Wayne State University" },
  { name: "Portland", country: "United States", region: "usa", pop: "~0.64 million", industries: ["software", "outdoor brands", "food & beverage"], landmarks: ["Mount Hood views", "Forest Park"], districts: ["Pearl District", "Alberta Arts District"], university: "Portland State University" },
  { name: "Las Vegas", country: "United States", region: "usa", pop: "~0.66 million", industries: ["tourism", "entertainment", "conventions"], landmarks: ["the Las Vegas Strip", "the Fremont Street Experience"], districts: ["The Strip", "Downtown Las Vegas"], university: "University of Nevada, Las Vegas" },
  { name: "Miami", country: "United States", region: "usa", pop: "~0.44 million", industries: ["tourism", "finance", "tech startups"], landmarks: ["South Beach", "the Wynwood Walls"], districts: ["Brickell", "Wynwood"], university: "University of Miami" },
  { name: "Atlanta", country: "United States", region: "usa", pop: "~0.5 million", industries: ["film & media", "logistics", "fintech"], landmarks: ["the Georgia Aquarium", "Piedmont Park"], districts: ["Midtown", "Buckhead"], university: "Georgia Tech" },
  { name: "Minneapolis", country: "United States", region: "usa", pop: "~0.43 million", industries: ["retail", "healthcare", "design"], landmarks: ["the Walker Art Center", "Minneapolis Sculpture Garden"], districts: ["North Loop", "Northeast Minneapolis"], university: "University of Minnesota" },
  { name: "New Orleans", country: "United States", region: "usa", pop: "~0.37 million", industries: ["tourism", "hospitality", "tech"], landmarks: ["the French Quarter", "Jackson Square"], districts: ["French Quarter", "Garden District"], university: "Tulane University" },
  { name: "Salt Lake City", country: "United States", region: "usa", pop: "~0.2 million", industries: ["tech", "tourism", "finance"], landmarks: ["Temple Square", "the Wasatch Mountains"], districts: ["Downtown SLC", "Sugar House"], university: "University of Utah" },
  { name: "Tampa", country: "United States", region: "usa", pop: "~0.4 million", industries: ["finance", "healthcare", "tourism"], landmarks: ["Riverwalk", "Busch Gardens"], districts: ["Downtown Tampa", "Ybor City"], university: "University of South Florida" },
  { name: "Orlando", country: "United States", region: "usa", pop: "~0.31 million", industries: ["tourism", "entertainment", "tech"], landmarks: ["Walt Disney World", "Universal Studios"], districts: ["Lake Nona", "Downtown Orlando"], university: "University of Central Florida" },
  { name: "Pittsburgh", country: "United States", region: "usa", pop: "~0.3 million", industries: ["robotics", "healthcare", "education"], landmarks: ["the Duquesne Incline", "Point State Park"], districts: ["Downtown Pittsburgh", "Lawrenceville"], university: "Carnegie Mellon University" },
  { name: "Cincinnati", country: "United States", region: "usa", pop: "~0.31 million", industries: ["brands & consumer goods", "healthcare", "logistics"], landmarks: ["the Cincinnati Zoo", "the Roebling Bridge"], districts: ["Over-the-Rhine", "the Banks"], university: "University of Cincinnati" },

  // ── Canada (11) ───────────────────────────────────────────────────
  { name: "Toronto", country: "Canada", region: "canada", pop: "~2.9 million", industries: ["finance", "technology", "media"], landmarks: ["the CN Tower", "Royal Ontario Museum"], districts: ["Downtown Toronto", "Yorkville"], university: "University of Toronto" },
  { name: "Montreal", country: "Canada", region: "canada", pop: "~1.8 million", industries: ["AI research", "aerospace", "gaming"], landmarks: ["Mount Royal", "Old Montreal"], districts: ["Plateau Mont-Royal", "Old Montreal"], university: "McGill University" },
  { name: "Vancouver", country: "Canada", region: "canada", pop: "~0.66 million", industries: ["film production", "tech", "clean energy"], landmarks: ["Stanley Park", "Capilano Suspension Bridge"], districts: ["Gastown", "Kitsilano"], university: "University of British Columbia" },
  { name: "Calgary", country: "Canada", region: "canada", pop: "~1.3 million", industries: ["energy", "technology", "finance"], landmarks: ["the Calgary Tower", "Stampede Park"], districts: ["Downtown Calgary", "Kensington"], university: "University of Calgary" },
  { name: "Edmonton", country: "Canada", region: "canada", pop: "~1.0 million", industries: ["oil & gas", "healthcare", "tech"], landmarks: ["West Edmonton Mall", "the Alberta Legislature"], districts: ["Downtown Edmonton", "Whyte Avenue"], university: "University of Alberta" },
  { name: "Ottawa", country: "Canada", region: "canada", pop: "~1.0 million", industries: ["government", "tech", "defense"], landmarks: ["Parliament Hill", "Rideau Canal"], districts: ["ByWard Market", "Glebe"], university: "Carleton University" },
  { name: "Winnipeg", country: "Canada", region: "canada", pop: "~0.75 million", industries: ["finance", "manufacturing", "agriculture"], landmarks: ["the Forks", "the Canadian Human Rights Museum"], districts: ["Exchange District", "the Forks"], university: "University of Manitoba" },
  { name: "Quebec City", country: "Canada", region: "canada", pop: "~0.54 million", industries: ["tourism", "insurance", "tech"], landmarks: ["Chateau Frontenac", "the Plains of Abraham"], districts: ["Old Quebec", "Sainte-Foy"], university: "Université Laval" },
  { name: "Halifax", country: "Canada", region: "canada", pop: "~0.44 million", industries: ["tech", "ocean research", "universities"], landmarks: ["Citadel Hill", "the Halifax Harbour"], districts: ["Downtown Halifax", "North End"], university: "Dalhousie University" },
  { name: "Victoria", country: "Canada", region: "canada", pop: "~0.09 million", industries: ["government", "tourism", "tech"], landmarks: ["the Inner Harbour", "Butchart Gardens"], districts: ["Downtown Victoria", "Fernwood"], university: "University of Victoria" },
  { name: "Saskatoon", country: "Canada", region: "canada", pop: "~0.27 million", industries: ["agriculture", "biotech", "mining"], landmarks: ["the Meewasin Valley", "Delta Bessborough Hotel"], districts: ["Broadway Avenue", "Nutana"], university: "University of Saskatchewan" },

  // ── United Kingdom & Ireland (12) ─────────────────────────────────
  { name: "London", country: "United Kingdom", region: "uk-ireland", pop: "~8.9 million", industries: ["finance", "fintech", "creative industries"], landmarks: ["the Tower of London", "the London Eye"], districts: ["Shoreditch", "the City of London"], university: "Imperial College London" },
  { name: "Manchester", country: "United Kingdom", region: "uk-ireland", pop: "~0.55 million", industries: ["media", "tech", "professional services"], landmarks: ["the John Rylands Library", "Manchester Cathedral"], districts: ["the Northern Quarter", "Spinningfields"], university: "University of Manchester" },
  { name: "Birmingham", country: "United Kingdom", region: "uk-ireland", pop: "~1.1 million", industries: ["manufacturing", "finance", "professional services"], landmarks: ["the Library of Birmingham", "the Bullring"], districts: ["the Jewellery Quarter", "Digbeth"], university: "University of Birmingham" },
  { name: "Leeds", country: "United Kingdom", region: "uk-ireland", pop: "~0.79 million", industries: ["finance", "legal", "healthcare"], landmarks: ["Leeds Town Hall", "the Royal Armouries"], districts: ["the Calls", "Headingley"], university: "University of Leeds" },
  { name: "Glasgow", country: "United Kingdom", region: "uk-ireland", pop: "~0.63 million", industries: ["engineering", "finance", "creative media"], landmarks: ["the Kelvingrove Art Gallery", "Glasgow Cathedral"], districts: ["the Merchant City", "Finnieston"], university: "University of Glasgow" },
  { name: "Edinburgh", country: "United Kingdom", region: "uk-ireland", pop: "~0.53 million", industries: ["fintech", "tourism", "universities"], landmarks: ["Edinburgh Castle", "Arthur's Seat"], districts: ["the Old Town", "Leith"], university: "University of Edinburgh" },
  { name: "Liverpool", country: "United Kingdom", region: "uk-ireland", pop: "~0.5 million", industries: ["logistics", "healthcare", "creative industries"], landmarks: ["the Royal Albert Dock", "Liverpool Cathedral"], districts: ["the Baltic Triangle", "Ropewalks"], university: "University of Liverpool" },
  { name: "Bristol", country: "United Kingdom", region: "uk-ireland", pop: "~0.47 million", industries: ["aerospace", "tech", "creative industries"], landmarks: ["the Clifton Suspension Bridge", "Bristol Harbour"], districts: ["the Harbourside", "Gloucester Road"], university: "University of Bristol" },
  { name: "Sheffield", country: "United Kingdom", region: "uk-ireland", pop: "~0.56 million", industries: ["manufacturing", "healthcare", "tech"], landmarks: ["the Peak District edge", "Sheffield Winter Garden"], districts: ["the Cultural Industries Quarter", "Kelham Island"], university: "University of Sheffield" },
  { name: "Newcastle", country: "United Kingdom", region: "uk-ireland", pop: "~0.3 million", industries: ["tech", "engineering", "healthcare"], landmarks: ["the Tyne Bridge", "Grey Street"], districts: ["Quayside", "Ouseburn"], university: "Newcastle University" },
  { name: "Belfast", country: "United Kingdom", region: "uk-ireland", pop: "~0.34 million", industries: ["tech", "cybersecurity", "film & TV"], landmarks: ["Belfast City Hall", "the Titanic Quarter"], districts: ["the Cathedral Quarter", "Stranmillis"], university: "Queen's University Belfast" },
  { name: "Dublin", country: "Ireland", region: "uk-ireland", pop: "~0.59 million", industries: ["tech", "finance", "pharmaceuticals"], landmarks: ["Trinity College", "the Guinness Storehouse"], districts: ["the Docklands", "Temple Bar"], university: "Trinity College Dublin" },

  // ── Europe (20) ───────────────────────────────────────────────────
  { name: "Paris", country: "France", region: "europe", pop: "~2.1 million", industries: ["luxury", "tech", "creative industries"], landmarks: ["the Eiffel Tower", "the Louvre"], districts: ["the Marais", "La Défense"], university: "Sorbonne University" },
  { name: "Berlin", country: "Germany", region: "europe", pop: "~3.7 million", industries: ["startups", "tech", "creative industries"], landmarks: ["the Brandenburg Gate", "the Berlin Wall Memorial"], districts: ["Mitte", "Kreuzberg"], university: "Humboldt University of Berlin" },
  { name: "Munich", country: "Germany", region: "europe", pop: "~1.5 million", industries: ["automotive", "engineering", "insurtech"], landmarks: ["Marienplatz", "the Englischer Garten"], districts: ["Maxvorstadt", "Schwabing"], university: "Ludwig Maximilian University of Munich" },
  { name: "Amsterdam", country: "Netherlands", region: "europe", pop: "~0.9 million", industries: ["finance", "tech", "creative industries"], landmarks: ["the Rijksmuseum", "the Anne Frank House"], districts: ["Jordaan", "the Zuidas"], university: "University of Amsterdam" },
  { name: "Brussels", country: "Belgium", region: "europe", pop: "~1.2 million", industries: ["EU institutions", "finance", "tech"], landmarks: ["the Grand Place", "the Atomium"], districts: ["the European Quarter", "Saint-Gilles"], university: "Université libre de Bruxelles" },
  { name: "Zurich", country: "Switzerland", region: "europe", pop: "~0.44 million", industries: ["banking", "insurtech", "biotech"], landmarks: ["Lake Zurich", "the Old Town"], districts: ["the Old Town", "Zurich West"], university: "ETH Zurich" },
  { name: "Geneva", country: "Switzerland", region: "europe", pop: "~0.2 million", industries: ["diplomacy", "finance", "tech"], landmarks: ["the Jet d'Eau", "the United Nations"], districts: ["Carouge", "the Old Town"], university: "University of Geneva" },
  { name: "Vienna", country: "Austria", region: "europe", pop: "~1.9 million", industries: ["tech", "finance", "tourism"], landmarks: ["Schönbrunn Palace", "St. Stephen's Cathedral"], districts: ["the Innere Stadt", "the MuseumsQuartier"], university: "University of Vienna" },
  { name: "Milan", country: "Italy", region: "europe", pop: "~1.4 million", industries: ["fashion", "design", "finance"], landmarks: ["the Duomo", "the Galleria Vittorio Emanuele II"], districts: ["Brera", "the Navigli"], university: "Polytechnic University of Milan" },
  { name: "Rome", country: "Italy", region: "europe", pop: "~2.8 million", industries: ["tourism", "tech", "government"], landmarks: ["the Colosseum", "the Vatican"], districts: ["Trastevere", "the EUR district"], university: "Sapienza University of Rome" },
  { name: "Madrid", country: "Spain", region: "europe", pop: "~3.3 million", industries: ["finance", "tech", "tourism"], landmarks: ["the Royal Palace", "Retiro Park"], districts: ["Salamanca", "Malasaña"], university: "Complutense University of Madrid" },
  { name: "Barcelona", country: "Spain", region: "europe", pop: "~1.6 million", industries: ["tech", "tourism", "design"], landmarks: ["Sagrada Família", "Park Güell"], districts: ["Eixample", "El Born"], university: "University of Barcelona" },
  { name: "Lisbon", country: "Portugal", region: "europe", pop: "~0.55 million", industries: ["tech", "tourism", "fintech"], landmarks: ["the Jerónimos Monastery", "Belém Tower"], districts: ["Alfama", "the Chiado"], university: "University of Lisbon" },
  { name: "Porto", country: "Portugal", region: "europe", pop: "~0.24 million", industries: ["tech", "wine", "manufacturing"], landmarks: ["the Dom Luís I Bridge", "the Ribeira"], districts: ["the Ribeira", "Boavista"], university: "University of Porto" },
  { name: "Stockholm", country: "Sweden", region: "europe", pop: "~0.98 million", industries: ["tech", "gaming", "fintech"], landmarks: ["Gamla Stan", "the Vasa Museum"], districts: ["Södermalm", "Östermalm"], university: "KTH Royal Institute of Technology" },
  { name: "Oslo", country: "Norway", region: "europe", pop: "~0.7 million", industries: ["energy", "tech", "maritime"], landmarks: ["the Opera House", "the Vigeland Park"], districts: ["Grünerløkka", "Aker Brygge"], university: "University of Oslo" },
  { name: "Copenhagen", country: "Denmark", region: "europe", pop: "~0.66 million", industries: ["design", "tech", "life sciences"], landmarks: ["the Little Mermaid", "Tivoli Gardens"], districts: ["Nørrebro", "the Meatpacking District"], university: "University of Copenhagen" },
  { name: "Helsinki", country: "Finland", region: "europe", pop: "~0.66 million", industries: ["tech", "gaming", "clean tech"], landmarks: ["Suomenlinna", "the Helsinki Cathedral"], districts: ["Kallio", "Punavuori"], university: "University of Helsinki" },
  { name: "Warsaw", country: "Poland", region: "europe", pop: "~1.8 million", industries: ["IT outsourcing", "fintech", "tech"], landmarks: ["the Old Town", "the Palace of Culture"], districts: ["Mokotów", "Praga"], university: "University of Warsaw" },
  { name: "Prague", country: "Czech Republic", region: "europe", pop: "~1.3 million", industries: ["tech", "tourism", "automotive"], landmarks: ["Charles Bridge", "Prague Castle"], districts: ["Vinohrady", "the Old Town"], university: "Charles University" },

  // ── Australia & New Zealand (10) ─────────────────────────────────
  { name: "Sydney", country: "Australia", region: "australasia", pop: "~5.3 million", industries: ["finance", "tech", "creative industries"], landmarks: ["the Sydney Opera House", "the Harbour Bridge"], districts: ["Surry Hills", "the CBD"], university: "University of Sydney" },
  { name: "Melbourne", country: "Australia", region: "australasia", pop: "~5.0 million", industries: ["tech", "design", "finance"], landmarks: ["Federation Square", "the Royal Botanic Gardens"], districts: ["Fitzroy", "Southbank"], university: "University of Melbourne" },
  { name: "Brisbane", country: "Australia", region: "australasia", pop: "~2.6 million", industries: ["tech", "tourism", "mining support"], landmarks: ["South Bank Parklands", "Brisbane City Hall"], districts: ["Fortitude Valley", "South Brisbane"], university: "University of Queensland" },
  { name: "Perth", country: "Australia", region: "australasia", pop: "~2.1 million", industries: ["mining", "energy", "tech"], landmarks: ["Kings Park", "Rottnest Island"], districts: ["Northbridge", "the CBD"], university: "University of Western Australia" },
  { name: "Adelaide", country: "Australia", region: "australasia", pop: "~1.4 million", industries: ["defense", "tech", "wine"], landmarks: ["Adelaide Oval", "the Barossa Valley"], districts: ["the East End", "North Adelaide"], university: "University of Adelaide" },
  { name: "Gold Coast", country: "Australia", region: "australasia", pop: "~0.7 million", industries: ["tourism", "tech", "construction"], landmarks: ["Surfers Paradise beach", "the SkyPoint Observation Deck"], districts: ["Surfers Paradise", "Burleigh Heads"], university: "Bond University" },
  { name: "Canberra", country: "Australia", region: "australasia", pop: "~0.46 million", industries: ["government", "defense", "tech"], landmarks: ["Parliament House", "the National Gallery"], districts: ["Civic", "the Parliamentary Triangle"], university: "Australian National University" },
  { name: "Auckland", country: "New Zealand", region: "australasia", pop: "~1.7 million", industries: ["tech", "trade", "tourism"], landmarks: ["the Sky Tower", "Waiheke Island"], districts: ["Ponsonby", "the Viaduct Harbour"], university: "University of Auckland" },
  { name: "Wellington", country: "New Zealand", region: "australasia", pop: "~0.21 million", industries: ["government", "film & TV", "tech"], landmarks: ["Te Papa Museum", "the Beehive"], districts: ["the Cuba Quarter", "Thorndon"], university: "Victoria University of Wellington" },
  { name: "Christchurch", country: "New Zealand", region: "australasia", pop: "~0.4 million", industries: ["agriculture tech", "engineering", "education"], landmarks: ["the Botanic Gardens", "the Port Hills"], districts: ["the CBD", "New Regent Street"], university: "University of Canterbury" },

  // ── Asia & Middle East (10) ──────────────────────────────────────
  { name: "Dubai", country: "United Arab Emirates", region: "asia-middleeast", pop: "~3.6 million", industries: ["real estate", "tourism", "finance"], landmarks: ["the Burj Khalifa", "Palm Jumeirah"], districts: ["Downtown Dubai", "DIFC"], university: "University of Dubai" },
  { name: "Abu Dhabi", country: "United Arab Emirates", region: "asia-middleeast", pop: "~1.5 million", industries: ["energy", "finance", "tourism"], landmarks: ["the Sheikh Zayed Grand Mosque", "the Louvre Abu Dhabi"], districts: ["the Corniche", "Saadiyat Island"], university: "Khalifa University" },
  { name: "Riyadh", country: "Saudi Arabia", region: "asia-middleeast", pop: "~7.7 million", industries: ["finance", "energy", "tech"], landmarks: ["the Kingdom Centre", "the National Museum"], districts: ["Olaya", "King Abdullah Financial District"], university: "King Saud University" },
  { name: "Singapore", country: "Singapore", region: "asia-middleeast", pop: "~5.9 million", industries: ["finance", "tech", "logistics"], landmarks: ["Marina Bay Sands", "Gardens by the Bay"], districts: ["Marina Bay", "Tanjong Pagar"], university: "National University of Singapore" },
  { name: "Hong Kong", country: "Hong Kong", region: "asia-middleeast", pop: "~7.4 million", industries: ["finance", "trade", "logistics"], landmarks: ["Victoria Peak", "the Star Ferry"], districts: ["Central", "Kowloon"], university: "University of Hong Kong" },
  { name: "Tokyo", country: "Japan", region: "asia-middleeast", pop: "~14 million", industries: ["technology", "finance", "consumer brands"], landmarks: ["the Tokyo Tower", "Senso-ji Temple"], districts: ["Shibuya", "Shinjuku"], university: "University of Tokyo" },
  { name: "Seoul", country: "South Korea", region: "asia-middleeast", pop: "~9.4 million", industries: ["technology", "K-pop & media", "finance"], landmarks: ["Gyeongbokgung Palace", "N Seoul Tower"], districts: ["Gangnam", "Hongdae"], university: "Seoul National University" },
  { name: "Mumbai", country: "India", region: "asia-middleeast", pop: "~20 million", industries: ["finance", "Bollywood", "tech"], landmarks: ["the Gateway of India", "Marine Drive"], districts: ["Bandra", "Powai"], university: "University of Mumbai" },
  { name: "Bangalore", country: "India", region: "asia-middleeast", pop: "~13 million", industries: ["software", "AI", "startups"], landmarks: ["the Vidhana Soudha", "Cubbon Park"], districts: ["Indiranagar", "Koramangala"], university: "Indian Institute of Science" },
  { name: "Bangkok", country: "Thailand", region: "asia-middleeast", pop: "~10 million", industries: ["tourism", "e-commerce", "finance"], landmarks: ["the Grand Palace", "Wat Arun"], districts: ["Sukhumvit", "Sathorn"], university: "Chulalongkorn University" },

  // ── Africa (3) ────────────────────────────────────────────────────
  { name: "Lagos", country: "Nigeria", region: "africa", pop: "~15 million", industries: ["fintech", "media", "tech"], landmarks: ["the Lekki Conservation Centre", "the National Theatre"], districts: ["Victoria Island", "Lekki"], university: "University of Lagos" },
  { name: "Nairobi", country: "Kenya", region: "africa", pop: "~4.4 million", industries: ["tech", "finance", "agriculture"], landmarks: ["the Nairobi National Park", "the Kenyatta International Convention Centre"], districts: ["Westlands", "Kilimani"], university: "University of Nairobi" },
  { name: "Cape Town", country: "South Africa", region: "africa", pop: "~4.7 million", industries: ["tech", "tourism", "finance"], landmarks: ["Table Mountain", "the V&A Waterfront"], districts: ["the CBD", "Woodstock"], university: "University of Cape Town" },

  // ── Latin America (4) ─────────────────────────────────────────────
  { name: "Mexico City", country: "Mexico", region: "latam", pop: "~9.2 million", industries: ["finance", "tech", "manufacturing"], landmarks: ["the Zócalo", "Chapultepec Park"], districts: ["Polanco", "Condesa"], university: "UNAM" },
  { name: "Sao Paulo", country: "Brazil", region: "latam", pop: "~12.3 million", industries: ["finance", "tech", "creative industries"], landmarks: ["the São Paulo Cathedral", "Ibirapuera Park"], districts: ["Paulista Avenue", "Vila Madalena"], university: "University of São Paulo" },
  { name: "Buenos Aires", country: "Argentina", region: "latam", pop: "~3.1 million", industries: ["tech", "design", "tourism"], landmarks: ["the Obelisco", "Casa Rosada"], districts: ["Palermo", "San Telmo"], university: "University of Buenos Aires" },
  { name: "Bogota", country: "Colombia", region: "latam", pop: "~7.7 million", industries: ["tech", "finance", "logistics"], landmarks: ["Monserrate", "the Gold Museum"], districts: ["Chapinero", "Usaquén"], university: "University of the Andes" },
];

export function citySlug(city: City): string {
  return city.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}