import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen theme-bg theme-text">
      <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6">
        <header className="glass-panel hairline mb-8 rounded-2xl px-6 py-5">
          <Link href="/" className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300 hover:underline">← Back to Studio</Link>
          <h1 className="mt-3 text-2xl font-black tracking-tight text-white">Privacy Policy</h1>
          <p className="mt-1 text-xs text-slate-400">Last updated: August 2026</p>
        </header>

        <div className="glass-panel hairline space-y-6 rounded-2xl px-6 py-8 text-sm leading-relaxed text-slate-300">
          <section>
            <h2 className="mb-2 text-base font-bold text-white">1. Overview</h2>
            <p>
              AI Resume Builder ("the Service"), operated by Kaywebservice Enterprise Solutions, helps you create resumes,
              cover letters, and ATS analyses. We keep your data minimal and use it only to operate the Service.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-bold text-white">2. Information We Process</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li><strong className="text-white">Form data you enter</strong> (name, contact details, work experience, education, and the job description you paste) — used only to generate your documents.</li>
              <li><strong className="text-white">Browser storage (localStorage)</strong> — your drafts, selected template, and your PRO unlock status are saved on your own device. Clearing your browser data removes them.</li>
              <li><strong className="text-white">Anonymous analytics events</strong> (e.g., "resume generated") — used to understand feature usage, without personal details.</li>
              <li><strong className="text-white">Email address</strong> — when you share a resume/cover letter link or save your email, we store it to contact you about the Service.</li>
              <li><strong className="text-white">Payment records</strong> — when you purchase PRO/PRO+, payments are processed by Creem (our Merchant of Record). We store only the order reference, product purchased, and amount to grant and verify access.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-bold text-white">3. How AI &amp; Documents Work</h2>
            <p>
              Resume, cover letter, and ATS analyses are generated by a local AI engine (Ollama). Your resume content and
              pasted job descriptions are sent to the local server to generate documents and are not sold or shared with
              third parties.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-bold text-white">4. Sharing</h2>
            <p>
              When you use the Share feature, the Resume you chose to share is stored on our database and visible to
              anyone with the share link. Do not share sensitive information you wish to keep private.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-bold text-white">5. Payments</h2>
            <p>
              Payments are processed by <a href="https://creem.io" target="_blank" rel="noopener noreferrer" className="text-blue-300 underline">Creem</a>, our Merchant of Record.
              Creem handles card processing, taxes, and receipts under its own privacy policy. We never see or store your
              full card details.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-bold text-white">6. Data Retention &amp; Your Rights</h2>
            <p>
              You may clear locally stored drafts at any time through your browser. To request deletion of data we hold
              (share links, leads, orders), email us and we will remove it within 30 days.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-bold text-white">7. Contact</h2>
            <p>Email: <a href="mailto:kaywebservice@gmail.com" className="text-blue-300 underline">kaywebservice@gmail.com</a></p>
          </section>
        </div>
      </div>
    </main>
  );
}