export interface ResumeTheme {
  id: string;
  name: string;
  background: string;
  headerBg: string;
  headerText: string;
  accent: string;
  text: string;
  border: string;
  font: string;
  layout: "classic" | "sidebar";
  premium?: boolean;
}

export const resumeThemes: ResumeTheme[] = [
  {
    id: "ats",
    name: "ATS Classic",
    background: "#ffffff",
    headerBg: "#ffffff",
    headerText: "#111827",
    accent: "#2563eb",
    text: "#1f2937",
    border: "#d1d5db",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "modern",
    name: "Modern Blue",
    background: "#ffffff",
    headerBg: "#2563eb",
    headerText: "#ffffff",
    accent: "#2563eb",
    text: "#1f2937",
    border: "#93c5fd",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "executive",
    name: "Executive Black",
    background: "#ffffff",
    headerBg: "#111827",
    headerText: "#ffffff",
    accent: "#111827",
    text: "#1f2937",
    border: "#374151",
    font: "Georgia, serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "minimal",
    name: "Minimal White",
    background: "#ffffff",
    headerBg: "#ffffff",
    headerText: "#1118293",
    accent: "#9ca3af",
    text: "#1118293",
    border: "#e5e7eb",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "creative",
    name: "Creative Sidebar",
    background: "#ffffff",
    headerBg: "#7c3aed",
    headerText: "#ffffff",
    accent: "#7c3aed",
    text: "#1f2937",
    border: "#ddd6fe",
    font: "Arial, sans-serif",
    layout: "sidebar",
    premium: false,
  },

  {
    id: "corporate",
    name: "Corporate Gray",
    background: "#ffffff",
    headerBg: "#4b5563",
    headerText: "#ffffff",
    accent: "#4b5563",
    text: "#1f2937",
    border: "#d1d5db",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "serif",
    name: "Elegant Serif",
    background: "#ffffff",
    headerBg: "#92400e",
    headerText: "#ffffff",
    accent: "#92400e",
    text: "#1f2937",
    border: "#fbbf24",
    font: "Georgia, serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "tech",
    name: "Tech Professional",
    background: "#ffffff",
    headerBg: "#0f172a",
    headerText: "#22c55e",
    accent: "#22c55e",
    text: "#1f2937",
    border: "#22c55e",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "gold",
    name: "Premium Gold",
    background: "#ffffff",
    headerBg: "#b45309",
    headerText: "#ffffff",
    accent: "#f59e0b",
    text: "#1f2937",
    border: "#fbbf24",
    font: "Georgia, serif",
    layout: "classic",
    premium: false,
  },

  {
    id: "contemporary",
    name: "Contemporary",
    background: "#ffffff",
    headerBg: "#0891b2",
    headerText: "#ffffff",
    accent: "#0891b2",
    text: "#1f2937",
    border: "#67e8f9",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "crimson",
    name: "Bold Crimson",
    background: "#fffafa",
    headerBg: "#991b1b",
    headerText: "#ffffff",
    accent: "#dc2626",
    text: "#292524",
    border: "#fecaca",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "ocean",
    name: "Oceanic",
    background: "#f0f9ff",
    headerBg: "#075985",
    headerText: "#ffffff",
    accent: "#0284c7",
    text: "#0f172a",
    border: "#bae6fd",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "slate",
    name: "Slate Minimal",
    background: "#f8fafc",
    headerBg: "#334155",
    headerText: "#ffffff",
    accent: "#475569",
    text: "#1e293b",
    border: "#cbd5e1",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "forest",
    name: "Forest Green",
    background: "#f7fee7",
    headerBg: "#166534",
    headerText: "#ffffff",
    accent: "#15803d",
    text: "#1c1917",
    border: "#bbf7d0",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "rose",
    name: "Rose Professional",
    background: "#fff1f2",
    headerBg: "#9f1239",
    headerText: "#ffffff",
    accent: "#e11d48",
    text: "#27272a",
    border: "#fecdd3",
    font: "Georgia, serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "indigo",
    name: "Indigo Ledger",
    background: "#eef2ff",
    headerBg: "#3730a3",
    headerText: "#ffffff",
    accent: "#4f46e5",
    text: "#1e1b4b",
    border: "#c7d2fe",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "amber",
    name: "Amber Portfolio",
    background: "#fffbeb",
    headerBg: "#92400e",
    headerText: "#ffffff",
    accent: "#d97706",
    text: "#292524",
    border: "#fde68a",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "midnight",
    name: "Midnight Editorial",
    background: "#f8fafc",
    headerBg: "#020617",
    headerText: "#ffffff",
    accent: "#0f172a",
    text: "#0f172a",
    border: "#94a3b8",
    font: "Georgia, serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "canvas",
    name: "Clean Canvas",
    background: "#ffffff",
    headerBg: "#ffffff",
    headerText: "#1118293",
    accent: "#0891b2",
    text: "#1118293",
    border: "#e5e7eb",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: false,
  },
  {
    id: "violet",
    name: "Violet Studio",
    background: "#faf5ff",
    headerBg: "#6d28d9",
    headerText: "#ffffff",
    accent: "#7c3aed",
    text: "#2e1065",
    border: "#ddd6fe",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: false,
  },

  // ---------- PREMIUM TEMPLATES ----------
  {
    id: "platinum",
    name: "Platinum Prestige",
    background: "#ffffff",
    headerBg: "#0b1223",
    headerText: "#fbbf24",
    accent: "#f59e0b",
    text: "#111827",
    border: "#d97706",
    font: "Georgia, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "arctic",
    name: "Arctic Cool",
    background: "#f0fdfa",
    headerBg: "#0d9488",
    headerText: "#ffffff",
    accent: "#0d9488",
    text: "#0f1729",
    border: "#99f6e4",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "rose-gold",
    name: "Rose Gold Metallic",
    background: "#fff5f6",
    headerBg: "#be123c",
    headerText: "#fce7f3",
    accent: "#db2763",
    text: "#29252c",
    border: "#fda4af",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "obsidian",
    name: "Obsidian Dark",
    background: "#18181b",
    headerBg: "#000000",
    headerText: "#f59e0b",
    accent: "#f59e0b",
    text: "#e4e4e7",
    border: "#3f3f46",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "ivory",
    name: "Ivory Luxe",
    background: "#fffff8",
    headerBg: "#fefce8",
    headerText: "#854d0e",
    accent: "#ca8a04",
    text: "#1c1716",
    border: "#fef08a",
    font: "Georgia, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "steel",
    name: "Brushed Steel",
    background: "#eff0f2",
    headerBg: "#475569",
    headerText: "#f1f5f9",
    accent: "#64748b",
    text: "#1e293b",
    border: "#cbd5e1",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "copper",
    name: "Copper Flame",
    background: "#ffffff",
    headerBg: "#7c2d12",
    headerText: "#fed7aa",
    accent: "#ea580c",
    text: "#292524",
    border: "#fec9a9",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "midnight-blue",
    name: "Midnight Navy",
    background: "#0f1e3d",
    headerBg: "#1e3a8a",
    headerText: "#ffffff",
    accent: "#60a5fa",
    text: "#cbd5e1",
    border: "#33415c",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "emerald",
    name: "Emerald Opulent",
    background: "#052e2e",
    headerBg: "#064e35",
    headerText: "#bbf7d0",
    accent: "#10b981",
    text: "#d1fae5",
    border: "#6ee7b7",
    font: "Georgia, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "coral",
    name: "Coral Reef",
    background: "#fff1ed",
    headerBg: "#ff6b6b",
    headerText: "#ffffff",
    accent: "#f97316",
    text: "#372a29",
    border: "#fec5b0",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "graphite",
    name: "Graphite Professional",
    background: "#f1f3f5",
    headerBg: "#2d3748",
    headerText: "#edf2f7",
    accent: "#4a5568",
    text: "#1a2029",
    border: "#cbd5e1",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "lavender",
    name: "Lavender Fields",
    background: "#faf5ff",
    headerBg: "#5b21b6",
    headerText: "#f3e8ff",
    accent: "#a78bfa",
    text: "#27114c",
    border: "#d8b4fe",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "charcoal",
    name: "Charcoal Edge",
    background: "#2d2d2d",
    headerBg: "#111111",
    headerText: "#e5e7eb",
    accent: "#f59e0b",
    text: "#cbd5e1",
    border: "#3f3f46",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "pearl",
    name: "Pearl Essence",
    background: "#ffffff",
    headerBg: "#f8fafc",
    headerText: "#0f1729",
    accent: "#94a3b8",
    text: "#1e293b",
    border: "#cbd5e1",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "ruby",
    name: "Ruby Intensity",
    background: "#fff5f5",
    headerBg: "#7f1d1d",
    headerText: "#fecaca",
    accent: "#ef4444",
    text: "#292524",
    border: "#fca5a5",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "silver",
    name: "Silver Stream",
    background: "#f8fafc",
    headerBg: "#64748b",
    headerText: "#f1f5f9",
    accent: "#94a3b8",
    text: "#0f1729",
    border: "#cbd5e1",
    font: "Georgia, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "azure",
    name: "Azure Mist",
    background: "#f0f9ff",
    headerBg: "#0284c7",
    headerText: "#f0fdfa",
    accent: "#06b6d4",
    text: "#0c2a33",
    border: "#7dd3fc",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "onyx",
    name: "Onyx Elegance",
    background: "#0a0a0f",
    headerBg: "#171717",
    headerText: "#fafaf9",
    accent: "#d1d5db",
    text: "#d1d5db",
    border: "#374151",
    font: "Georgia, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "sunset",
    name: "Sunset Gradient",
    background: "#ffffff",
    headerBg: "#ea580c",
    headerText: "#ffffff",
    accent: "#f59e0b",
    text: "#451a03",
    border: "#fca3a3",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "polaroid",
    name: "Polaroid Frame",
    background: "#ffffff",
    headerBg: "#dbeafe",
    headerText: "#1e40af",
    accent: "#3b82f6",
    text: "#1e3a8a",
    border: "#bfdbfe",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "noir",
    name: "Noir Statement",
    background: "#ffffff",
    headerBg: "#0f172a",
    headerText: "#ffffff",
    accent: "#f8fafc",
    text: "#0f172a",
    border: "#cbd5e1",
    font: "Courier New, monospace",
    layout: "classic",
    premium: true,
  },
  {
    id: "cobalt",
    name: "Cobalt Voltage",
    background: "#f8fafc",
    headerBg: "#1e40af",
    headerText: "#ffffff",
    accent: "#2563eb",
    text: "#1e293b",
    border: "#bfdbfe",
    font: "Arial, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "sage",
    name: "Sage Serenity",
    background: "#ffffff",
    headerBg: "#3f6212",
    headerText: "#ffffff",
    accent: "#65a30d",
    text: "#14532d",
    border: "#d9f99d",
    font: "Georgia, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "terra",
    name: "Terra Clay",
    background: "#fffcf9",
    headerBg: "#9a3412",
    headerText: "#ffffff",
    accent: "#ea580c",
    text: "#431407",
    border: "#fdba74",
    font: "Trebuchet MS, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "skyline",
    name: "Skyline Urban",
    background: "#ffffff",
    headerBg: "#0c4a6e",
    headerText: "#ffffff",
    accent: "#0891b2",
    text: "#164e63",
    border: "#a5f3fc",
    font: "Segoe UI, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "berry",
    name: "Berry Crush",
    background: "#ffffff",
    headerBg: "#9d174d",
    headerText: "#ffffff",
    accent: "#db2777",
    text: "#500724",
    border: "#fbcfe8",
    font: "Verdana, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "nebula",
    name: "Nebula Dark",
    background: "#0b1220",
    headerBg: "#111a2e",
    headerText: "#e2e8f0",
    accent: "#818cf8",
    text: "#e2e8f0",
    border: "#312e81",
    font: "Helvetica, sans-serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "bronze",
    name: "Bronze Heritage",
    background: "#fffdf5",
    headerBg: "#92400e",
    headerText: "#ffffff",
    accent: "#b45309",
    text: "#451a03",
    border: "#fde68a",
    font: "Garamond, serif",
    layout: "classic",
    premium: true,
  },
  {
    id: "jade",
    name: "Jade Flow",
    background: "#ffffff",
    headerBg: "#065f46",
    headerText: "#ffffff",
    accent: "#059669",
    text: "#064e3b",
    border: "#a7f3d0",
    font: "Tahoma, sans-serif",
    layout: "classic",
    premium: true,
  },
];

export function getTheme(id: string): ResumeTheme {
  return (
    resumeThemes.find((theme) => theme.id === id) ||
    resumeThemes[0]
  );
}
